// SET AUTH
export const SET_AUTH = 'SET_AUTH'
// SIGN IN/UP
export const TOGGLE_SIGN_PAGE = 'TOGGLE_SIGN_PAGE' //used
export const SIGN_IN_USER = 'SIGN_IN_USER'
//PROFILES
export const REGISTER_USER = 'REGISTER_USER'
export const FETCH_PROFILES = 'FETCH_PROFILES'
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const DELETE_PROFILE = 'DELETE_PROFILE'
export const ADD_PROFILE = 'ADD_PROFILE'
// MED LOG ACTIONS
export const FETCH_USER_SESSIONS = 'FETCH_USER_SESSIONS'
export const FETCH_SESSIONS = 'FETCH_SESSION'
